name: Feature request
description: Propose an improvement for Dallas AI Direct
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / opportunity
      description: What constraint are we removing?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed change
    validations:
      required: true
  - type: textarea
    id: privacy
    attributes:
      label: Privacy impact
      description: Any risk to attendee data boundary?
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: Acceptance criteria
      placeholder: |
        - [ ]
        - [ ]
    validations:
      required: true
